### PR TITLE
Fix README links, Add TikTok support

### PR DESCRIPTION
**Pull request by danielimmke**
TikTok has become very popular and this will let people add embeds to their site. Also, I fixed some incorrect links in the README.

### CODE REVIEW

**Comment by raae** [comment]
This looks great, could you add a tik tok example in the `example-content/posts/` folder so I can more easily verify that its working?

**Comment by danielimmke** [comment]
There should be one in there already

**Comment by raae** [comment]
I will get this reviewed and merged before hacktober is over!

**Comment by danielimmke** [comment]
No rush, I'm not participating in Hacktoberfest. I use this package on my personal site and needed TikTok support.

**Comment by danielimmke** [comment]
Hey, any update on this?

**Pull request closed without merging**
